server: 
  port: 8003 
  context-path: /redeem
logging: 
  level: 
    root: INFO 
    org.hibernate: INFO 
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE 
    com.itmuch.youran.persistence: ERROR 
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://user:password123@localhost:8761/eureka/    # 指定注册中心的地址 
  instance: 
    preferIpAddress: true 
spring:
  application: 
    name: redeem-server
  redis:
    host: 127.0.0.1
    pool:
      max-idle: 8
      max-wait: 1000
      max-active: 300
    port: 6379
  datasource:
    dbcp:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/redeem
      username: root
      password: 1qazxsw2