server: 
  port: 8001 
  context-path: /redeem
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://user:password123@localhost:8761/eureka/    # 指定注册中心的地址 
  instance: 
    preferIpAddress: true 
spring: 
  application: 
    name: redeem_web